data:
  data_dir: data  # Root data directory

  prepro_dir: prepro  # Subfolder for preprocessed data
  train_dir: train    # Subfolder for training data
  test_dir: test      # Subfolder for test data

  # Specify file names within each subfolder
  prepro_files:
    - datos_fred_procesados.csv
    - descripciones.txt
    - residualsHOUTSMW.pkl
    - data_normalized.pkl
    - x_slow_fast.pkl
    - ydata.pkl
