load("favarBBE/data/results_factor_7.RData")
ls()
library(readxl)
library(readr)
library(boot)
library(tsDyn)
library(vars)
library(repr)
library(dplyr)
library(dfms)
library(xts)
library(vars)
library(fbi)
library(forecast)
library(OOS)
library(zoo)
print(ics)
plot(ics)
screeplot(ics, main="Scree plot")
screeplot(ics, type="ev", main="Scree plot")
screeplot(ics,type="cum.pve", main="Scree plot")
