install.packages("reticulate")
install.packages("here")
install.packages("readr")
library(reticulate)
library(here)
library(readr)
setwd("C:/Users/user/Desktop/Tesis_Maestria/Favar")
use_python("../python/python.exe")
pickle_slow_fast <- "../data/prepro/x_slow_fast.pkl"
df_slow_fast <- readRDS(pickle_slow_fast)
print(head(df_slow_fast))
