#use_python("../python/python.exe")
df=read_csv("../data/prepro/sfr.csv")
slow=read_csv("../data/prepro/slow_columns.csv")
fast=read_csv("../data/prepro/fast_columns.csv")
print(head(df))
print(dim(df))
print(colnames(df))
print(head(slow))
slow_list <- unlist(slow$slow)
print(slow_list)